include:
  - local: '.common-ci.yml'
  - project: nvidia/container-infrastructure/aws-kube-ci
    file: aws-kube-ci.yml
    ref: 20.12.07

e2e_tests:
  stage: e2e_tests
  image: alpine
  script:
    - source .VERSION_INFO
    - source aws-kube-ci/hostname
    - apk add --no-cache openssh-client rsync
    - rsync -e "ssh -i aws-kube-ci/key -o StrictHostKeyChecking=no" -av --exclude="vendor/" "${CI_PROJECT_DIR}" "${instance_hostname}:~/"
    - rc=0
    - (ssh -i aws-kube-ci/key -o StrictHostKeyChecking=no ${instance_hostname} "cd ~/gpu-operator/tests && ./ci-run-e2e.sh ${CI_REGISTRY_IMAGE} ${VERSION}") || rc=$?
    - rsync -e "ssh -i aws-kube-ci/key" -av "${instance_hostname}:/tmp/logs/" logs
    - exit $rc
  dependencies:
    - aws_kube_setup
    - versioning
  artifacts:
    when: always
    paths:
      - logs/

aws_kube_setup:
  extends: .aws_kube_setup
  except:
    - schedules

aws_kube_clean:
  extends: .aws_kube_clean
  except:
    - schedules
