scorecard:
  # Setting a global scorecard option
  # Change below to CSV bundle directory path
  bundle: $HOME/git/src/github.com/operator-framework/operator-registry/bundles/gpu-operator.1.3.0
  output: json
  plugins:
    # `basic` tests configured to test GPU Operator CR
    - basic:
        cr-manifest:
          - "deploy/crds/nvidia.com_v1_clusterpolicies_cr.yaml"
        namespace: operator 
        init-timeout: 60
    # `olm` tests configured to test GPU Operator CR
    - olm:
        cr-manifest:
          - "deploy/crds/nvidia.com_v1_clusterpolicies_cr.yaml"
        csv-path: "deploy/olm-catalog/gpu-operator/1.3.0/gpu-operator.v1.3.0.clusterserviceversion.yaml"
        init-timeout: 60
        namespace: operator
