global:
  localRegistry: ""

# Default values for gpu-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nfd:
  enabled: true

node-feature-discovery:
  worker:
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"

    options:
      sources:
        pci:
          deviceLabelFields:
          - vendor

platform:
  openshift: false

operator:
  registry: ""
  repository: nvidia
  image: gpu-operator
# If not set, the tag defaults to Chart.AppVersion
  tag: "1.1.7"

  defaultRuntime: docker
  clusterversion: 0.0

  nodeSelector: {}

  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: ""
    effect: "NoSchedule"

  annotations:
    openshift.io/scc: restricted-readonly

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]

driver:
  registry: ""
  repository: nvidia
  image: driver
  version: "440.64.00"

toolkit:
  registry: ""
  repository: gcr.io/rec-repo
  image: container-toolkit
  version: 1.0.2-debian9

devicePlugin:
  registry: ""
  repository: nvidia
  image: k8s-device-plugin
  version: 1.0.0-beta6

dcgmExporter:
  registry: ""
  repository: nvidia
  image: dcgm-exporter
  version: 1.7.2-2.0.0-rc.9-ubuntu18.04
