{{- if .Values.global.extraImages }}
apiVersion: v1
kind: Pod
metadata:
  name: k8s-device-plugin
spec:
  containers:
  - name: k8s-device-plugin
    image: nvcr.io/nvidia/k8s-device-plugin:v0.7.1
    command: ["sh", "-c"]
    args:
      - exit 0
---
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-driver
spec:
  containers:
  - name: nvidia-driver
    image: gcr.io/rec-repo/nvidia-driver:440.64.00-debian9
    command: ["sh", "-c"]
    args:
      - exit 0
---
apiVersion: v1
kind: Pod
metadata:
  name: dcgm-exporter
spec:
  containers:
  - name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.0.13-2.1.2-ubuntu20.04
    command: ["sh", "-c"]
    args:
      - exit 0
---
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-sample-vectoradd
spec:
  containers:
  - name: nvidia-sample-vectoradd
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
    command: ["sh", "-c"]
    args:
      - exit 0
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-feature-discovery
spec:
  containers:
  - name: gpu-feature-discovery
    image: nvcr.io/nvidia/gpu-feature-discovery:v0.2.2
    command: ["sh", "-c"]
    args:
      - exit 0
---
apiVersion: v1
kind: Pod
metadata:
  name: container-toolkit
spec:
  containers:
  - name: container-toolkit
    image: gcr.io/rec-repo/container-toolkit:1.0.2-debian9
    command: ["sh", "-c"]
    args:
      - exit 0
{{- end }}
