{{- if .Values.global.extraImages }}
apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
  - name: kafka
    image: strimzi/kafka:0.16.2-kafka-2.4.0
    command: ["sh", "-c"]
    args:
      - exit 0
{{- end }}
