apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-device-plugin-validation
  name: nvidia-device-plugin-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  initContainers:
  - name: device-plugin-validation-init
    image: "FILLED BY THE OPERATOR"
    command: ['sh', '-c']
    args: ["until /tmp/vectorAdd; do echo waiting for nvidia drivers to be loaded; sleep 5; done"]
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
  containers:
    - name: device-plugin-validation
      image: "FILLED BY THE OPERATOR"
      # override command and args as validation is already done by initContainer
      command: ['sh', '-c']
      args: ["echo device-plugin validation is successful"]
      securityContext:
        allowPrivilegeEscalation: false
